Declare repoDir as output of reset task
ajoberstar/gradle-git-publish pull request #39
Opened 2017-10-20 03:53 UTC by ajoberstar

As of Gradle 4.2, when execution of a task begins, any "stale" outputs
will be deleted. All files under build and any declared outputs are
considered managed by Gradle. If other files happen to be in there,
Gradle will delete them.

The reset task did not declare any outputs, but created the
build/gitPublish directory and cloned the repo in there. When the copy
task rolls around, it sees some that cloned repo as stale files in its
output directory, since the copy task didn't put them there. Since they
are also under build, Gradle considers itself the owner and thinks it's
safe to delete them.

By declaring the repodir as an output, the intent is to prevent Gradle
from considering those stale outputs. We still need to be careful not to
make Gradle do up-to-date logic on the reset task, since that isn't
really possible to declare with normal Gradle input options.

This is intended to address #35.

[1] https://docs.gradle.org/4.2/release-notes.html#safer-handling-of-stale-output-files

2017-10-20 09:05 UTC, wolfs requested changes
I left some comments about also using `upToDateWhen { false }`. You could also consider to not use the `Copy` task, but use [`Project.copy`](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:copy(org.gradle.api.Action)) instead. Then not a single one of your tasks would be using incremental build.

2017-10-20 09:05 UTC, wolfs commented on src/main/groovy/org/ajoberstar/gradle/git/publish/GitPublishPlugin.groovy
> +      outputs.dir(extension.repoDir)
I guess you also should do `upToDateWhen { false }` to make sure the task is always executed. Given that is has no inputs that is what would happen if the output directory contents would not change. Alternatively, you could also add the inputs to the task (git commit hash, branch, remote?) if that is possible. Same goes for the other tasks in here.
In the future, we may provide you with a way to declare that there should not be any up-to-date checks for a task, so you don't pay the performance penalty of checking all the files in the repository for changes.

2017-10-20 12:32 UTC, ajoberstar commented
Thanks @wolfs. I wasn't quite sure how to deal with these tasks that work in the same directory or the ones that are doing remote work rather than outputting a concrete file. I might be able to come up with some inputs, but maybe it does make more sense to drop the Copy task. I'll look into this more this weekend.

2017-10-21 19:52 UTC, ajoberstar commented
I've reworked this to use project.copy. Seems like the most straightforward option at this point.

2017-10-21 19:52 UTC, merged